### ISSUE TITLE
Getting elasticsearch failure on keyword search

### ISSUE THREAD

**Issue by LindsayYoung** [propublica/congress#512]
For example:

When I try:
`congress.api.sunlightfoundation.com/bills/search?keywords=africa&apikey={key}`
I get back:

```
{
    "error": {
        "backtrace": [
            "/projects/congress-api/.rbenv/versions/2.1.1/lib/ruby/gems/2.1.0/gems/elasticsearch-transport-1.0.1/lib/elasticsearch/transport/transport/base.rb:132:in `__raise_transport_error'",
            "/projects/congress-api/.rbenv/versions/2.1.1/lib/ruby/gems/2.1.0/gems/elasticsearch-transport-1.0.1/lib/elasticsearch/transport/transport/base.rb:227:in `perform_request'",
            "/projects/congress-api/.rbenv/versions/2.1.1/lib/ruby/gems/2.1.0/gems/elasticsearch-transport-1.0.1/lib/elasticsearch/transport/transport/http/faraday.rb:20:in `perform_request'",
            "/projects/congress-api/.rbenv/versions/2.1.1/lib/ruby/gems/2.1.0/gems/elasticsearch-transport-1.0.1/lib/elasticsearch/transport/client.rb:102:in `perform_request'",
            "/projects/congress-api/.rbenv/versions/2.1.1/lib/ruby/gems/2.1.0/gems/elasticsearch-api-1.0.1/lib/elasticsearch/api/actions/search.rb:148:in `search'",
            "/projects/congress-api/congress/versions/20150608161638/api/searchable.rb:160:in `search_for'",
            "/projects/congress-api/congress/versions/20150608161638/congress.rb:75:in `block in <top (required)>'",
            "/projects/congress-api/.rbenv/versions/2.1.1/lib/ruby/gems/2.1.0/gems/sinatra-1.4.4/lib/sinatra/base.rb:1593:in `call'",
            "/projects/congress-api/.rbenv/versions/2.1.1/lib/ruby/gems/2.1.0/gems/sinatra-1.4.4/lib/sinatra/base.rb:1593:in `block in compile!'",
            "/projects/congress-api/.rbenv/versions/2.1.1/lib/ruby/gems/2.1.0/gems/sinatra-1.4.4/lib/sinatra/base.rb:957:in `[]'",
            "/projects/congress-api/.rbenv/versions/2.1.1/lib/ruby/gems/2.1.0/gems/sinatra-1.4.4/lib/sinatra/base.rb:957:in `block (3 levels) in route!'",
            "/projects/congress-api/.rbenv/versions/2.1.1/lib/ruby/gems/2.1.0/gems/sinatra-1.4.4/lib/sinatra/base.rb:976:in `route_eval'",
            "/projects/congress-api/.rbenv/versions/2.1.1/lib/ruby/gems/2.1.0/gems/newrelic_rpm-3.9.7.266/lib/new_relic/agent/instrumentation/sinatra.rb:135:in `route_eval_with_newrelic'",
            "/projects/congress-api/.rbenv/versions/2.1.1/lib/ruby/gems/2.1.0/gems/sinatra-1.4.4/lib/sinatra/base.rb:957:in `block (2 levels) in route!'",
            "/projects/congress-api/.rbenv/versions/2.1.1/lib/ruby/gems/2.1.0/gems/sinatra-1.4.4/lib/sinatra/base.rb:997:in `block in process_route'",
            "/projects/congress-api/.rbenv/versions/2.1.1/lib/ruby/gems/2.1.0/gems/sinatra-1.4.4/lib/sinatra/base.rb:995:in `catch'",
            "/projects/congress-api/.rbenv/versions/2.1.1/lib/ruby/gems/2.1.0/gems/sinatra-1.4.4/lib/sinatra/base.rb:995:in `process_route'",
            "/projects/congress-api/.rbenv/versions/2.1.1/lib/ruby/gems/2.1.0/gems/newrelic_rpm-3.9.7.266/lib/new_relic/agent/instrumentation/sinatra.rb:115:in `process_route_with_newrelic'",
            "/projects/congress-api/.rbenv/versions/2.1.1/lib/ruby/gems/2.1.0/gems/sinatra-1.4.4/lib/sinatra/base.rb:955:in `block in route!'",
            "/projects/congress-api/.rbenv/versions/2.1.1/lib/ruby/gems/2.1.0/gems/sinatra-1.4.4/lib/sinatra/base.rb:954:in `each'",
            "/projects/congress-api/.rbenv/versions/2.1.1/lib/ruby/gems/2.1.0/gems/sinatra-1.4.4/lib/sinatra/base.rb:954:in `route!'",
            "/projects/congress-api/.rbenv/versions/2.1.1/lib/ruby/gems/2.1.0/gems/sinatra-1.4.4/lib/sinatra/base.rb:1067:in `block in dispatch!'",
            "/projects/congress-api/.rbenv/versions/2.1.1/lib/ruby/gems/2.1.0/gems/sinatra-1.4.4/lib/sinatra/base.rb:1049:in `block in invoke'",
            "/projects/congress-api/.rbenv/versions/2.1.1/lib/ruby/gems/2.1.0/gems/sinatra-1.4.4/lib/sinatra/base.rb:1049:in `catch'",
            "/projects/congress-api/.rbenv/versions/2.1.1/lib/ruby/gems/2.1.0/gems/sinatra-1.4.4/lib/sinatra/base.rb:1049:in `invoke'",
            "/projects/congress-api/.rbenv/versions/2.1.1/lib/ruby/gems/2.1.0/gems/sinatra-1.4.4/lib/sinatra/base.rb:1064:in `dispatch!'",
            "/projects/congress-api/.rbenv/versions/2.1.1/lib/ruby/gems/2.1.0/gems/newrelic_rpm-3.9.7.266/lib/new_relic/agent/instrumentation/sinatra.rb:166:in `dispatch_and_notice_errors_with_newrelic'",
            "/projects/congress-api/.rbenv/versions/2.1.1/lib/ruby/gems/2.1.0/gems/newrelic_rpm-3.9.7.266/lib/new_relic/agent/instrumentation/sinatra.rb:152:in `block in dispatch_with_newrelic'",
            "/projects/congress-api/.rbenv/versions/2.1.1/lib/ruby/gems/2.1.0/gems/newrelic_rpm-3.9.7.266/lib/new_relic/agent/instrumentation/controller_instrumentation.rb:365:in `perform_action_with_newrelic_trace'",
            "/projects/congress-api/.rbenv/versions/2.1.1/lib/ruby/gems/2.1.0/gems/newrelic_rpm-3.9.7.266/lib/new_relic/agent/instrumentation/sinatra.rb:149:in `dispatch_with_newrelic'",
            "/projects/congress-api/.rbenv/versions/2.1.1/lib/ruby/gems/2.1.0/gems/sinatra-1.4.4/lib/sinatra/base.rb:889:in `block in call!'",
            "/projects/congress-api/.rbenv/versions/2.1.1/lib/ruby/gems/2.1.0/gems/sinatra-1.4.4/lib/sinatra/base.rb:1049:in `block in invoke'",
            "/projects/congress-api/.rbenv/versions/2.1.1/lib/ruby/gems/2.1.0/gems/sinatra-1.4.4/lib/sinatra/base.rb:1049:in `catch'",
            "/projects/congress-api/.rbenv/versions/2.1.1/lib/ruby/gems/2.1.0/gems/sinatra-1.4.4/lib/sinatra/base.rb:1049:in `invoke'",
            "/projects/congress-api/.rbenv/versions/2.1.1/lib/ruby/gems/2.1.0/gems/sinatra-1.4.4/lib/sinatra/base.rb:889:in `call!'",
            "/projects/congress-api/.rbenv/versions/2.1.1/lib/ruby/gems/2.1.0/gems/sinatra-1.4.4/lib/sinatra/base.rb:877:in `call'",
            "/projects/congress-api/.rbenv/versions/2.1.1/lib/ruby/gems/2.1.0/gems/newrelic_rpm-3.9.7.266/lib/new_relic/rack/browser_monitoring.rb:23:in `traced_call'",
            "/projects/congress-api/.rbenv/versions/2.1.1/lib/ruby/gems/2.1.0/gems/newrelic_rpm-3.9.7.266/lib/new_relic/agent/instrumentation/middleware_tracing.rb:55:in `call'",
            "/projects/congress-api/.rbenv/versions/2.1.1/lib/ruby/gems/2.1.0/gems/newrelic_rpm-3.9.7.266/lib/new_relic/rack/agent_hooks.rb:26:in `traced_call'",
            "/projects/congress-api/.rbenv/versions/2.1.1/lib/ruby/gems/2.1.0/gems/newrelic_rpm-3.9.7.266/lib/new_relic/agent/instrumentation/middleware_tracing.rb:55:in `call'",
            "/projects/congress-api/.rbenv/versions/2.1.1/lib/ruby/gems/2.1.0/gems/rack-1.5.2/lib/rack/nulllogger.rb:9:in `call'",
            "/projects/congress-api/.rbenv/versions/2.1.1/lib/ruby/gems/2.1.0/gems/newrelic_rpm-3.9.7.266/lib/new_relic/agent/instrumentation/middleware_tracing.rb:57:in `call'",
            "/projects/congress-api/.rbenv/versions/2.1.1/lib/ruby/gems/2.1.0/gems/rack-1.5.2/lib/rack/head.rb:11:in `call'",
            "/projects/congress-api/.rbenv/versions/2.1.1/lib/ruby/gems/2.1.0/gems/newrelic_rpm-3.9.7.266/lib/new_relic/agent/instrumentation/middleware_tracing.rb:57:in `call'",
            "/projects/congress-api/.rbenv/versions/2.1.1/lib/ruby/gems/2.1.0/gems/rack-1.5.2/lib/rack/methodoverride.rb:21:in `call'",
            "/projects/congress-api/.rbenv/versions/2.1.1/lib/ruby/gems/2.1.0/gems/newrelic_rpm-3.9.7.266/lib/new_relic/agent/instrumentation/middleware_tracing.rb:57:in `call'",
            "/projects/congress-api/.rbenv/versions/2.1.1/lib/ruby/gems/2.1.0/gems/sinatra-1.4.4/lib/sinatra/base.rb:180:in `call'",
            "/projects/congress-api/.rbenv/versions/2.1.1/lib/ruby/gems/2.1.0/gems/newrelic_rpm-3.9.7.266/lib/new_relic/agent/instrumentation/middleware_tracing.rb:57:in `call'",
            "/projects/congress-api/.rbenv/versions/2.1.1/lib/ruby/gems/2.1.0/gems/sinatra-1.4.4/lib/sinatra/base.rb:2004:in `call'",
            "/projects/congress-api/.rbenv/versions/2.1.1/lib/ruby/gems/2.1.0/gems/sinatra-1.4.4/lib/sinatra/base.rb:1469:in `block in call'",
            "/projects/congress-api/.rbenv/versions/2.1.1/lib/ruby/gems/2.1.0/gems/sinatra-1.4.4/lib/sinatra/base.rb:1778:in `synchronize'",
            "/projects/congress-api/.rbenv/versions/2.1.1/lib/ruby/gems/2.1.0/gems/sinatra-1.4.4/lib/sinatra/base.rb:1469:in `call'",
            "/projects/congress-api/.rbenv/versions/2.1.1/lib/ruby/gems/2.1.0/gems/newrelic_rpm-3.9.7.266/lib/new_relic/agent/instrumentation/middleware_tracing.rb:57:in `call'",
            "/projects/congress-api/.rbenv/versions/2.1.1/lib/ruby/gems/2.1.0/gems/unicorn-4.8.2/lib/unicorn/http_server.rb:572:in `process_client'",
            "/projects/congress-api/.rbenv/versions/2.1.1/lib/ruby/gems/2.1.0/gems/unicorn-4.8.2/lib/unicorn/http_server.rb:666:in `worker_loop'",
            "/projects/congress-api/.rbenv/versions/2.1.1/lib/ruby/gems/2.1.0/gems/unicorn-4.8.2/lib/unicorn/http_server.rb:521:in `spawn_missing_workers'",
            "/projects/congress-api/.rbenv/versions/2.1.1/lib/ruby/gems/2.1.0/gems/unicorn-4.8.2/lib/unicorn/http_server.rb:140:in `start'",
            "/projects/congress-api/.rbenv/versions/2.1.1/lib/ruby/gems/2.1.0/gems/unicorn-4.8.2/bin/unicorn:126:in `<top (required)>'",
            "/projects/congress-api/.rbenv/versions/2.1.1/bin/unicorn:23:in `load'",
            "/projects/congress-api/.rbenv/versions/2.1.1/bin/unicorn:23:in `<main>'"
        ],
        "message": "[503] {\"error\":\"SearchPhaseExecutionException[Failed to execute phase [query], all shards failed]\",\"status\":503}",
        "type": "Elasticsearch::Transport::Transport::Errors::ServiceUnavailable"
    }
}
```

**Comment by crdunwel** [comment]
Hey @LindsayYoung . Yep we're experiencing ES issues. Working to resolve it.

**Comment by crdunwel** [comment]
@LindsayYoung want to give it a try? Working for me now.
